### ISSUE TITLE
Am I right?

### ISSUE THREAD

**Issue by iRYO400** [getsetgames/Swipe#6]
Are you reviving this plugin for newest UE4 versions?

**Comment by derekvanvliet** [comment]
@iRYO400 this plugin should work with 4.10. Are you having a problem with it?

**Comment by iRYO400** [comment]
I haven't installed it yet. 
The reason why I asked, Why these people don't use it? https://forums.unrealengine.com/showthread.php?992-Swipes
I thought your plugin doesn't work, so they don't use it
sorry for my English

**Comment by derekvanvliet** [comment]
@iRYO400 it looks like they're discussing ways to do some of the things that this plugin allows, but it doesn't look like they've come across it yet. I posted a link to that thread - maybe it'll help.

Thanks for the heads up!

**Comment by iRYO400** [comment]
Sorry for offtop. 
I heard that gameDNA works on implementation networking over WiFi for mobile devices, is that true?

**Comment by gameDNA-Helix** [comment]
Hi iRYO400,
it's not true. Where did you hear about it? And why you asked in this repo? :)

**Comment by iRYO400** [comment]
Here I got an answer https://www.youtube.com/watch?v=Y2wYx5EM3GE in the comments
I don't have your contacts, so I asked here )

**Comment by gameDNA-Helix** [comment]
iRYO400,
he told that he hope we make plugin but currently we don't have any plans to do this but... maybe in the future :+1: who knows :dancer:
